// qr_generator/dashboard/src/components/PartnerCreate.tsx
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { CreatePartnerRequest, PartnerType } from '../types/dashboard';
import { partnerService } from '../services/partnerService';

const PartnerCreate: React.FC = () => {
  const navigate = useNavigate();
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState(false);

  const [formData, setFormData] = useState<CreatePartnerRequest>({
    name: '',
    address: '',
    whatsapp: '',
    phone: '',
    description: '',
    website: '',
    instagram: '',
    facebook: '',
    partnerType: 'RESTAURANT',
    profileImage: '',
    coverImage: ''
  });

  const [profileImageFile, setProfileImageFile] = useState<File | null>(null);
  const [coverImageFile, setCoverImageFile] = useState<File | null>(null);
  const [galleryFiles, setGalleryFiles] = useState<File[]>([]);
  const [uploadingImages, setUploadingImages] = useState(false);

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
    const { name, value } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: value
    }));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setError(null);
    setSuccess(false);

    try {
      // Primero crear el partner
      const newPartner = await partnerService.createPartner(formData);
      
      // Luego subir las imágenes si existen
      if (profileImageFile || coverImageFile || galleryFiles.length > 0) {
        setUploadingImages(true);
        
        if (profileImageFile) {
          await partnerService.uploadProfileImage(newPartner.id, profileImageFile);
        }
        
        if (coverImageFile) {
          await partnerService.uploadCoverImage(newPartner.id, coverImageFile);
        }
        
        // Subir imágenes de galería
        if (galleryFiles.length > 0) {
          for (let i = 0; i < galleryFiles.length; i++) {
            const file = galleryFiles[i];
            await partnerService.uploadGalleryImage(newPartner.id, file, `Imagen ${i + 1}`, i);
          }
        }
      }
      
      setSuccess(true);
      setTimeout(() => {
        navigate('/partners');
      }, 2000);
    } catch (err) {
      setError('Error al crear partner: ' + (err as Error).message);
    } finally {
      setLoading(false);
      setUploadingImages(false);
    }
  };

  const handleCancel = () => {
    navigate('/partners');
  };

  const handleProfileImageChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      setProfileImageFile(file);
    }
  };

  const handleCoverImageChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      setCoverImageFile(file);
    }
  };

  const handleGalleryChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = Array.from(e.target.files || []);
    const currentCount = galleryFiles.length;
    const newCount = currentCount + files.length;
    
    if (newCount > 10) {
      setError(`Máximo 10 imágenes permitidas. Ya tienes ${currentCount} imágenes seleccionadas.`);
      return;
    }
    
    setGalleryFiles(prev => [...prev, ...files]);
    setError(null); // Limpiar error si existe
  };

  const removeGalleryFile = (index: number) => {
    setGalleryFiles(prev => prev.filter((_, i) => i !== index));
  };

  return (
    <div className="max-w-4xl mx-auto">
      {/* Header */}
      <div className="mb-8">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-3xl font-bold text-gray-900">Crear Nuevo Partner</h1>
            <p className="mt-2 text-gray-600">Complete la información del nuevo partner</p>
          </div>
          <button
            onClick={handleCancel}
            className="btn-secondary flex items-center space-x-2"
          >
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 19l-7-7m0 0l7-7m-7 7h18" />
            </svg>
            <span>Volver</span>
          </button>
        </div>
      </div>

      {/* Success Message */}
      {success && (
        <div className="mb-6 bg-green-50 border border-green-200 text-green-700 px-4 py-3 rounded-lg">
          <div className="flex items-center">
            <svg className="w-5 h-5 mr-2" fill="currentColor" viewBox="0 0 20 20">
              <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
            </svg>
            Partner creado exitosamente. Redirigiendo...
          </div>
        </div>
      )}

      {/* Error Message */}
      {error && (
        <div className="mb-6 bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded-lg">
          {error}
        </div>
      )}

      {/* Form */}
      <div className="card">
        <form onSubmit={handleSubmit} className="space-y-6">
          {/* Basic Information */}
          <div>
            <h3 className="text-lg font-medium text-gray-900 mb-4">Información Básica</h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div>
                <label htmlFor="name" className="block text-sm font-medium text-gray-700 mb-2">
                  Nombre del Partner *
                </label>
                <input
                  type="text"
                  id="name"
                  name="name"
                  value={formData.name}
                  onChange={handleInputChange}
                  required
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                  placeholder="Ej: Restaurante El Buen Sabor"
                />
              </div>

              <div>
                <label htmlFor="partnerType" className="block text-sm font-medium text-gray-700 mb-2">
                  Tipo de Partner *
                </label>
                <select
                  id="partnerType"
                  name="partnerType"
                  value={formData.partnerType}
                  onChange={handleInputChange}
                  required
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                >
                  <option value="RESTAURANT">Restaurante</option>
                  <option value="VETERINARIAN">Veterinario</option>
                  <option value="PET_SHOP">Pet Shop</option>
                  <option value="PET_FRIENDLY">Pet Friendly</option>
                  <option value="OTHER">Otro</option>
                </select>
              </div>
            </div>
          </div>

          {/* Address */}
          <div>
            <label htmlFor="address" className="block text-sm font-medium text-gray-700 mb-2">
              Dirección *
            </label>
            <input
              type="text"
              id="address"
              name="address"
              value={formData.address}
              onChange={handleInputChange}
              required
              className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
              placeholder="Ej: Av. San Martín 123, Centro"
            />
          </div>

          {/* Contact Information */}
          <div>
            <h3 className="text-lg font-medium text-gray-900 mb-4">Información de Contacto</h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div>
                <label htmlFor="phone" className="block text-sm font-medium text-gray-700 mb-2">
                  Teléfono
                </label>
                <input
                  type="tel"
                  id="phone"
                  name="phone"
                  value={formData.phone}
                  onChange={handleInputChange}
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                  placeholder="Ej: +54 9 11 1234-5678"
                />
              </div>

              <div>
                <label htmlFor="whatsapp" className="block text-sm font-medium text-gray-700 mb-2">
                  WhatsApp
                </label>
                <input
                  type="tel"
                  id="whatsapp"
                  name="whatsapp"
                  value={formData.whatsapp}
                  onChange={handleInputChange}
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                  placeholder="Ej: +54 9 11 1234-5678"
                />
              </div>
            </div>
          </div>

          {/* Website and Social Media */}
          <div>
            <h3 className="text-lg font-medium text-gray-900 mb-4">Sitio Web y Redes Sociales</h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div>
                <label htmlFor="website" className="block text-sm font-medium text-gray-700 mb-2">
                  Sitio Web
                </label>
                <input
                  type="url"
                  id="website"
                  name="website"
                  value={formData.website}
                  onChange={handleInputChange}
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                  placeholder="Ej: https://www.ejemplo.com"
                />
              </div>

              <div>
                <label htmlFor="instagram" className="block text-sm font-medium text-gray-700 mb-2">
                  Instagram
                </label>
                <input
                  type="text"
                  id="instagram"
                  name="instagram"
                  value={formData.instagram || ''}
                  onChange={handleInputChange}
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                  placeholder="Ej: @restaurante_ejemplo"
                />
              </div>

              <div>
                <label htmlFor="facebook" className="block text-sm font-medium text-gray-700 mb-2">
                  Facebook
                </label>
                <input
                  type="text"
                  id="facebook"
                  name="facebook"
                  value={formData.facebook || ''}
                  onChange={handleInputChange}
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                  placeholder="Ej: Restaurante Ejemplo"
                />
              </div>
            </div>
          </div>

          {/* Description */}
          <div>
            <label htmlFor="description" className="block text-sm font-medium text-gray-700 mb-2">
              Descripción
            </label>
            <textarea
              id="description"
              name="description"
              value={formData.description}
              onChange={handleInputChange}
              rows={4}
              className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
              placeholder="Descripción del partner, servicios que ofrece, horarios, etc."
            />
          </div>

          {/* Images Section */}
          <div>
            <h3 className="text-lg font-medium text-gray-900 mb-4">Imágenes</h3>
            
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              {/* Profile Image */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Imagen de Perfil
                </label>
                <div className="space-y-4">
                  {profileImageFile && (
                    <div className="relative">
                      <img
                        src={URL.createObjectURL(profileImageFile)}
                        alt="Vista previa de imagen de perfil"
                        className="w-32 h-32 object-cover rounded-lg border border-gray-300"
                      />
                    </div>
                  )}
                  <input
                    type="file"
                    accept="image/*"
                    onChange={handleProfileImageChange}
                    className="block w-full text-sm text-gray-500 file:mr-4 file:py-2 file:px-4 file:rounded-full file:border-0 file:text-sm file:font-semibold file:bg-blue-50 file:text-blue-700 hover:file:bg-blue-100"
                  />
                </div>
              </div>

              {/* Cover Image */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Imagen de Portada
                </label>
                <div className="space-y-4">
                  {coverImageFile && (
                    <div className="relative">
                      <img
                        src={URL.createObjectURL(coverImageFile)}
                        alt="Vista previa de imagen de portada"
                        className="w-full h-32 object-cover rounded-lg border border-gray-300"
                      />
                    </div>
                  )}
                  <input
                    type="file"
                    accept="image/*"
                    onChange={handleCoverImageChange}
                    className="block w-full text-sm text-gray-500 file:mr-4 file:py-2 file:px-4 file:rounded-full file:border-0 file:text-sm file:font-semibold file:bg-blue-50 file:text-blue-700 hover:file:bg-blue-100"
                  />
                </div>
              </div>
            </div>

            {/* Gallery */}
            <div className="mt-6">
              <div className="flex items-center justify-between mb-2">
                <label className="block text-sm font-medium text-gray-700">
                  Galería de Imágenes
                </label>
                <span className="text-sm text-gray-500">
                  {galleryFiles.length}/10 imágenes
                </span>
              </div>
              <div className="space-y-4">
                <input
                  type="file"
                  accept="image/*"
                  multiple
                  onChange={handleGalleryChange}
                  className="block w-full text-sm text-gray-500 file:mr-4 file:py-2 file:px-4 file:rounded-full file:border-0 file:text-sm file:font-semibold file:bg-blue-50 file:text-blue-700 hover:file:bg-blue-100"
                />
                
                {galleryFiles.length > 0 && (
                  <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                    {galleryFiles.map((file, index) => (
                      <div key={index} className="relative">
                        <img
                          src={URL.createObjectURL(file)}
                          alt={`Imagen ${index + 1}`}
                          className="w-full h-24 object-cover rounded-lg border border-gray-300"
                        />
                        <button
                          type="button"
                          onClick={() => removeGalleryFile(index)}
                          className="absolute -top-2 -right-2 bg-red-500 text-white rounded-full w-6 h-6 flex items-center justify-center text-xs hover:bg-red-600"
                        >
                          ×
                        </button>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            </div>
          </div>

          {/* Form Actions */}
          <div className="flex justify-end space-x-4 pt-6 border-t border-gray-200">
            <button
              type="button"
              onClick={handleCancel}
              className="btn-secondary"
              disabled={loading}
            >
              Cancelar
            </button>
            <button
              type="submit"
              className="btn-primary flex items-center space-x-2"
              disabled={loading || uploadingImages}
            >
              {loading || uploadingImages ? (
                <>
                  <div className="animate-spin rounded-full h-5 w-5 border-b-2 border-white"></div>
                  <span>{uploadingImages ? 'Subiendo imágenes...' : 'Creando...'}</span>
                </>
              ) : (
                <>
                  <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 6v6m0 0v6m0-6h6m-6 0H6" />
                  </svg>
                  <span>Crear Partner</span>
                </>
              )}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default PartnerCreate;

// frontend/src/app/pages/partner-create/partner-create.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { PartnersService, Partner } from 'src/app/services/partners.service';

@Component({
  selector: 'app-partner-create',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './partner-create.component.html',
  styleUrls: ['./partner-create.component.scss']
})
export class PartnerCreateComponent implements OnInit {
  partner: Partial<Partner> = {
    name: '',
    address: '',
    description: '',
    phone: '',
    whatsapp: '',
    website: '',
    partnerType: 'OTHER',
    status: 'ACTIVE',
    latitude: 0,
    longitude: 0,
    positioning: 0
  };

  loading = false;
  error: string | null = null;
  success = false;

  partnerTypes = [
    { value: 'VETERINARIAN', label: 'Veterinaria' },
    { value: 'PET_SHOP', label: 'Pet Shop' },
    { value: 'RESTAURANT', label: 'Restaurante' },
    { value: 'OTHER', label: 'Otro' }
  ];

  // Galería de imágenes
  galleryImages: File[] = [];
  galleryImageUrls: string[] = [];

  constructor(
    private partnersService: PartnersService,
    private router: Router
  ) {}

  ngOnInit(): void {}

  onGalleryImagesSelected(event: any) {
    const files = event.target.files;
    if (files) {
      for (let i = 0; i < files.length; i++) {
        const file = files[i];
        if (file.type.startsWith('image/')) {
          this.galleryImages.push(file);
          // Crear URL temporal para preview
          const reader = new FileReader();
          reader.onload = (e: any) => {
            this.galleryImageUrls.push(e.target.result);
          };
          reader.readAsDataURL(file);
        }
      }
    }
  }

  removeGalleryImage(index: number) {
    this.galleryImages.splice(index, 1);
    this.galleryImageUrls.splice(index, 1);
  }

  async onSubmit() {
    if (!this.validateForm()) {
      return;
    }

    this.loading = true;
    this.error = null;

    try {
      // Crear el partner
      const newPartner = await this.partnersService.createPartner(this.partner as any).toPromise();
      
      if (newPartner && this.galleryImages.length > 0) {
        // Subir imágenes de la galería
        for (let i = 0; i < this.galleryImages.length; i++) {
          await this.uploadGalleryImage(newPartner.id, this.galleryImages[i], i);
        }
      }

      this.success = true;
      setTimeout(() => {
        this.router.navigate(['/partners']);
      }, 2000);

    } catch (err) {
      this.error = 'Error al crear el partner: ' + (err as Error).message;
    } finally {
      this.loading = false;
    }
  }

  private async uploadGalleryImage(partnerId: number, file: File, order: number) {
    const formData = new FormData();
    formData.append('image', file);
    formData.append('order', order.toString());

    try {
      const response = await fetch(`http://localhost:3333/api/partners/${partnerId}/gallery`, {
        method: 'POST',
        body: formData
      });

      if (!response.ok) {
        throw new Error('Error al subir imagen de galería');
      }
    } catch (error) {
      console.error('Error uploading gallery image:', error);
    }
  }

  private validateForm(): boolean {
    if (!this.partner.name?.trim()) {
      this.error = 'El nombre es requerido';
      return false;
    }
    if (!this.partner.address?.trim()) {
      this.error = 'La dirección es requerida';
      return false;
    }
    if (!this.partner.partnerType) {
      this.error = 'El tipo de partner es requerido';
      return false;
    }
    return true;
  }

  onCancel() {
    this.router.navigate(['/partners']);
  }
}

<!-- Hero Section -->
<section class="bg-gradient-to-br from-blue-50 to-green-50 py-16">
  <div class="container mx-auto px-4">
    <!-- Banner Promocional -->
    <div class="bg-gradient-to-r from-pink-100 via-orange-100 to-yellow-100 rounded-3xl p-8 mb-12 shadow-xl relative overflow-hidden">
      <!-- Elementos decorativos de fondo -->
      <div class="absolute top-0 right-0 w-32 h-32 bg-gradient-to-br from-yellow-200 to-orange-200 rounded-full opacity-30 transform translate-x-8 -translate-y-8"></div>
      <div class="absolute bottom-0 left-0 w-24 h-24 bg-gradient-to-br from-pink-200 to-red-200 rounded-full opacity-30 transform -translate-x-6 translate-y-6"></div>
      
      <div class="flex flex-col lg:flex-row items-center justify-between relative z-10">
        <div class="flex items-center mb-6 lg:mb-0">
          <div class="mr-6 relative">
            <div class="text-6xl font-bold text-yellow-500 mb-2 animate-pulse">✨</div>
            <div class="text-3xl font-bold text-red-600 bg-white px-3 py-1 rounded-full shadow-lg">NUEVO</div>
            <div class="absolute -top-2 -right-2 w-6 h-6 bg-red-500 rounded-full flex items-center justify-center">
              <span class="text-white text-xs font-bold">!</span>
            </div>
          </div>
          <div>
            <h1 class="text-3xl font-bold text-gray-800 mb-2">
              ¡Crear Nuevo Partner!
            </h1>
            <p class="text-lg text-gray-600">
              Agrega tu establecimiento a nuestra red de partners pet-friendly
            </p>
            <div class="flex items-center mt-3 space-x-2">
              <span class="bg-green-100 text-green-800 px-2 py-1 rounded-full text-xs font-medium">✅ Verificado</span>
              <span class="bg-blue-100 text-blue-800 px-2 py-1 rounded-full text-xs font-medium">🌟 Premium</span>
            </div>
          </div>
        </div>
        <div class="flex items-center space-x-6">
          <div class="text-center group">
            <div class="text-5xl group-hover:scale-110 transition-transform duration-300">🏢</div>
            <div class="text-sm text-gray-600 font-medium">Establecimiento</div>
            <div class="text-xs text-gray-500">Nuevo</div>
          </div>
          <div class="text-center group">
            <div class="text-5xl group-hover:scale-110 transition-transform duration-300">📸</div>
            <div class="text-sm text-gray-600 font-medium">Galería</div>
            <div class="text-xs text-gray-500">Imágenes</div>
          </div>
          <div class="text-center group">
            <div class="text-5xl group-hover:scale-110 transition-transform duration-300">📍</div>
            <div class="text-sm text-gray-600 font-medium">Ubicación</div>
            <div class="text-xs text-gray-500">GPS</div>
          </div>
        </div>
      </div>
    </div>

    <!-- Título Principal -->
    <div class="text-center mb-12">
      <div class="inline-flex items-center mb-4">
        <span class="text-4xl mr-3">🎯</span>
        <h2 class="text-4xl font-bold text-[#006455]">
          Crear Nuevo Partner
        </h2>
        <span class="text-4xl ml-3">🎯</span>
      </div>
      <p class="text-xl text-[#36454F] max-w-2xl mx-auto mb-6">
        Completa el formulario para agregar tu establecimiento a nuestra red
      </p>
    </div>
  </div>
</section>

<!-- Formulario -->
<section class="py-16 bg-white">
  <div class="container mx-auto px-4">
    <div class="max-w-4xl mx-auto">
      
      <!-- Mensajes de estado -->
      <div *ngIf="error" class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded-lg mb-6">
        {{ error }}
      </div>

      <div *ngIf="success" class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded-lg mb-6">
        ¡Partner creado exitosamente! Redirigiendo...
      </div>

      <!-- Formulario -->
      <form (ngSubmit)="onSubmit()" class="space-y-8">
        
        <!-- Información Básica -->
        <div class="bg-white rounded-3xl p-8 shadow-xl border border-gray-100">
          <h3 class="text-2xl font-bold text-[#006455] mb-6 flex items-center">
            <span class="text-3xl mr-3">📋</span>
            Información Básica
          </h3>
          
          <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div>
              <label class="block text-sm font-medium text-gray-700 mb-2">Nombre del Establecimiento *</label>
              <input 
                type="text" 
                [(ngModel)]="partner.name" 
                name="name"
                class="w-full px-4 py-3 border border-gray-300 rounded-xl focus:ring-2 focus:ring-[#006455] focus:border-transparent"
                placeholder="Ej: Hakuna Matata Pet Shop">
            </div>
            
            <div>
              <label class="block text-sm font-medium text-gray-700 mb-2">Tipo de Establecimiento *</label>
              <select 
                [(ngModel)]="partner.partnerType" 
                name="partnerType"
                class="w-full px-4 py-3 border border-gray-300 rounded-xl focus:ring-2 focus:ring-[#006455] focus:border-transparent">
                <option *ngFor="let type of partnerTypes" [value]="type.value">
                  {{ type.label }}
                </option>
              </select>
            </div>
            
            <div class="md:col-span-2">
              <label class="block text-sm font-medium text-gray-700 mb-2">Descripción</label>
              <textarea 
                [(ngModel)]="partner.description" 
                name="description"
                rows="4"
                class="w-full px-4 py-3 border border-gray-300 rounded-xl focus:ring-2 focus:ring-[#006455] focus:border-transparent"
                placeholder="Describe tu establecimiento, servicios, especialidades..."></textarea>
            </div>
          </div>
        </div>

        <!-- Información de Contacto -->
        <div class="bg-white rounded-3xl p-8 shadow-xl border border-gray-100">
          <h3 class="text-2xl font-bold text-[#006455] mb-6 flex items-center">
            <span class="text-3xl mr-3">📞</span>
            Información de Contacto
          </h3>
          
          <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div>
              <label class="block text-sm font-medium text-gray-700 mb-2">Dirección *</label>
              <input 
                type="text" 
                [(ngModel)]="partner.address" 
                name="address"
                class="w-full px-4 py-3 border border-gray-300 rounded-xl focus:ring-2 focus:ring-[#006455] focus:border-transparent"
                placeholder="Ej: Montevideo 209, Mendoza">
            </div>
            
            <div>
              <label class="block text-sm font-medium text-gray-700 mb-2">Teléfono</label>
              <input 
                type="tel" 
                [(ngModel)]="partner.phone" 
                name="phone"
                class="w-full px-4 py-3 border border-gray-300 rounded-xl focus:ring-2 focus:ring-[#006455] focus:border-transparent"
                placeholder="Ej: +54 261 123-4567">
            </div>
            
            <div>
              <label class="block text-sm font-medium text-gray-700 mb-2">WhatsApp</label>
              <input 
                type="tel" 
                [(ngModel)]="partner.whatsapp" 
                name="whatsapp"
                class="w-full px-4 py-3 border border-gray-300 rounded-xl focus:ring-2 focus:ring-[#006455] focus:border-transparent"
                placeholder="Ej: +54 9 261 123-4567">
            </div>
            
            <div>
              <label class="block text-sm font-medium text-gray-700 mb-2">Sitio Web</label>
              <input 
                type="url" 
                [(ngModel)]="partner.website" 
                name="website"
                class="w-full px-4 py-3 border border-gray-300 rounded-xl focus:ring-2 focus:ring-[#006455] focus:border-transparent"
                placeholder="Ej: https://www.miempresa.com">
            </div>
          </div>
        </div>

        <!-- Ubicación GPS -->
        <div class="bg-white rounded-3xl p-8 shadow-xl border border-gray-100">
          <h3 class="text-2xl font-bold text-[#006455] mb-6 flex items-center">
            <span class="text-3xl mr-3">📍</span>
            Ubicación GPS
          </h3>
          
          <div class="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div>
              <label class="block text-sm font-medium text-gray-700 mb-2">Latitud</label>
              <input 
                type="number" 
                [(ngModel)]="partner.latitude" 
                name="latitude"
                step="any"
                class="w-full px-4 py-3 border border-gray-300 rounded-xl focus:ring-2 focus:ring-[#006455] focus:border-transparent"
                placeholder="Ej: -32.8922082">
            </div>
            
            <div>
              <label class="block text-sm font-medium text-gray-700 mb-2">Longitud</label>
              <input 
                type="number" 
                [(ngModel)]="partner.longitude" 
                name="longitude"
                step="any"
                class="w-full px-4 py-3 border border-gray-300 rounded-xl focus:ring-2 focus:ring-[#006455] focus:border-transparent"
                placeholder="Ej: -68.8426918">
            </div>
            
            <div>
              <label class="block text-sm font-medium text-gray-700 mb-2">Posicionamiento</label>
              <input 
                type="number" 
                [(ngModel)]="partner.positioning" 
                name="positioning"
                class="w-full px-4 py-3 border border-gray-300 rounded-xl focus:ring-2 focus:ring-[#006455] focus:border-transparent"
                placeholder="Ej: 1">
            </div>
          </div>
          
          <div class="mt-4 p-4 bg-blue-50 rounded-xl">
            <p class="text-sm text-blue-700">
              💡 <strong>Consejo:</strong> Puedes obtener las coordenadas desde Google Maps. Haz clic derecho en tu ubicación y selecciona "¿Qué hay aquí?" para ver las coordenadas.
            </p>
          </div>
        </div>

        <!-- Galería de Imágenes -->
        <div class="bg-white rounded-3xl p-8 shadow-xl border border-gray-100">
          <h3 class="text-2xl font-bold text-[#006455] mb-6 flex items-center">
            <span class="text-3xl mr-3">📸</span>
            Galería de Imágenes
          </h3>
          
          <div class="space-y-6">
            <div>
              <label class="block text-sm font-medium text-gray-700 mb-2">Seleccionar Imágenes</label>
              <input 
                type="file" 
                multiple 
                accept="image/*"
                (change)="onGalleryImagesSelected($event)"
                class="w-full px-4 py-3 border border-gray-300 rounded-xl focus:ring-2 focus:ring-[#006455] focus:border-transparent">
              <p class="text-sm text-gray-500 mt-2">Puedes seleccionar múltiples imágenes. Formatos: JPG, PNG, GIF. Máximo 5MB por imagen.</p>
            </div>
            
            <!-- Preview de imágenes -->
            <div *ngIf="galleryImageUrls.length > 0" class="grid grid-cols-2 md:grid-cols-4 gap-4">
              <div *ngFor="let url of galleryImageUrls; let i = index" class="relative group">
                <img [src]="url" alt="Preview" class="w-full h-32 object-cover rounded-xl">
                <button 
                  type="button"
                  (click)="removeGalleryImage(i)"
                  class="absolute top-2 right-2 bg-red-500 text-white rounded-full w-6 h-6 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity">
                  ×
                </button>
              </div>
            </div>
          </div>
        </div>

        <!-- Botones de acción -->
        <div class="flex justify-end space-x-4">
          <button 
            type="button"
            (click)="onCancel()"
            class="px-8 py-3 bg-gray-500 hover:bg-gray-600 text-white rounded-xl font-medium transition-colors">
            Cancelar
          </button>
          <button 
            type="submit"
            [disabled]="loading"
            class="px-8 py-3 bg-[#006455] hover:bg-[#005544] text-white rounded-xl font-medium transition-colors disabled:opacity-50">
            <span *ngIf="loading" class="flex items-center">
              <div class="animate-spin rounded-full h-4 w-4 border-b-2 border-white mr-2"></div>
              Creando...
            </span>
            <span *ngIf="!loading">Crear Partner</span>
          </button>
        </div>
      </form>
    </div>
  </div>
</section>
